#!/bin/sh
#
# @name Tilt Wing Tricopter
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Jack Kovryzhenko <yzk0058@auburn.edu.
#
. ${R}etc/init.d/rc.vtol_defaults


param set-default PWM_AUX_DIS5 950
param set-default PWM_MAIN_RATE 400

param set-default VT_TYPE 1
param set-default VT_MOT_ID 12
param set-default VT_FW_MOT_OFFID 12
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_SC 0.17

set MAV_TYPE 21

set MIXER vtol_tilt_wing
set MIXER_AUX vtol_tilt_wing

set PWM_OUT 12
set PWM_AUX_OUT 12 #this will make aux channels be treated as ESCs
