#!/bin/sh
#
# @name Tilt Wing Tricopter
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Jack Kovryzhenko <yzk0058@auburn.edu.
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 servo 1
# @output AUX2 servo 2
# @output AUX3 servo 3
# @output AUX4 servo 4
# @output AUX5 servo 5
# @output AUX6 servo 6
# @output AUX7 servo 7
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default PWM_AUX_DIS5 950
param set-default PWM_MAIN_RATE 400

param set-default VT_TYPE 1
param set-default VT_MOT_ID 12
param set-default VT_FW_MOT_OFFID 12
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_SC 0.17

set MAV_TYPE 21

set MIXER vtol_tilt_wing
set MIXER_AUX vtol_tilt_wing

set PWM_OUT 1234
#set PWM_AUX_OUT 1234567 #this will make aux channels be treated as ESCs

#
# Start simulink modudes
#
sim_ctrl_mod start -f -p 42
